let javaQuestions = [
    { text: "What is JDBC and why is it important in Java applications?", mark: 10, imp: true },
    { text: "Explain the architecture of JDBC.", mark: 10, imp: false },
    { text: "What are the different types of JDBC drivers?", mark: 10, imp: true },
    { text: "Describe the main JDBC classes and interfaces.", mark: 10, imp: false },
    { text: "How do you create a simple JDBC application?", mark: 10, imp: true },
    { text: "What is the role of the Statement interface in JDBC?", mark: 5, imp: false },
    { text: "Explain the difference between Statement, PreparedStatement, and CallableStatement.", mark: 10, imp: true },
    { text: "What are ResultSet operations in JDBC?", mark: 10, imp: true },
    { text: "Describe the steps involved in executing a SQL query using JDBC.", mark: 5, imp: false },
    { text: "What is socket programming in Java?", mark: 5, imp: false },
    { text: "How do you work with URLs in Java?", mark: 5, imp: false },
    { text: "Explain the purpose of the InetAddress class in Java.", mark: 5, imp: false },
    { text: "What is the URLConnection class and how is it used?", mark: 5, imp: false },
    { text: "Describe the DataSocket class and its significance.", mark: 5, imp: false },
    { text: "Explain client-side and server-side programming concepts.", mark: 10, imp: true },
    { text: "What is an Applet in Java?", mark: 5, imp: false },
    { text: "Describe the life cycle of an Applet.", mark: 10, imp: true },
    { text: "What are the parameters that can be passed to an Applet?", mark: 5, imp: false },
    { text: "What is the Graphics class in Java?", mark: 5, imp: false },
    { text: "How does an Applet interact with its program?", mark: 10, imp: true },
    { text: "What is the Servlet API?", mark: 10, imp: true },
    { text: "Explain the Servlet interface.", mark: 10, imp: true },
    { text: "What is the difference between GenericServlet and HttpServlet?", mark: 10, imp: false },
    { text: "Describe the life cycle of a Servlet.", mark: 10, imp: true },
    { text: "How does a Servlet work?", mark: 10, imp: true },
    { text: "What are ServletRequest and ServletResponse?", mark: 5, imp: false },
    { text: "Explain Servlet collaboration and the role of RequestDispatcher.", mark: 10, imp: true },
    { text: "What is session tracking in Servlets?", mark: 10, imp: false },
    { text: "Describe the use of cookies in Servlets.", mark: 5, imp: false },
    { text: "What is JSP and how does it compare to Servlets?", mark: 10, imp: true },
    { text: "Explain the architecture of JSP.", mark: 10, imp: true },
    { text: "Describe the life cycle of a JSP.", mark: 10, imp: false },
    { text: "What are the scripting elements in JSP?", mark: 5, imp: false },
    { text: "What are JSP directives and how are they used?", mark: 5, imp: false },
    { text: "Explain the concept of implicit objects in JSP.", mark: 10, imp: true },
    { text: "What is Expression Language (EL) in JSP?", mark: 10, imp: false },
    { text: "Describe JSP Standard Tag Libraries (JSTL).", mark: 10, imp: true },
    { text: "What are formatting tags in JSP?", mark: 5, imp: false },
    { text: "Explain the use of XML tags in JSP.", mark: 5, imp: false },
    { text: "What is Struts2 and how does it fit into the Java ecosystem?", mark: 10, imp: true },
    { text: "What are the key components of the Struts2 framework?", mark: 10, imp: false },
    { text: "Explain the differences between Model 1 and Model 2 architecture in Struts.", mark: 10, imp: true },
    { text: "What is the ActionContext in Struts2?", mark: 5, imp: false },
    { text: "What is the ValueStack in Struts2?", mark: 5, imp: false },
    { text: "Describe the role of Interceptors in Struts2.", mark: 10, imp: true },
    { text: "What is the significance of Action in Struts2?", mark: 10, imp: true },
    { text: "Explain how Struts2 handles internationalization (i18n).", mark: 5, imp: false },
    { text: "What are the common challenges faced while working with Struts2?", mark: 5, imp: false },
    { text: "Describe the process of building a simple web application using Struts2.", mark: 10, imp: true },
];
module.exports = javaQuestions;