let adQuestion = [
    { text: "What is Android, and how does it differ from other mobile operating systems?", mark: 10, imp: true },
    { text: "What is the history of mobile software development, and how has Android evolved?", mark: 10, imp: false },
    { text: "What is the Open Handset Alliance, and how does it relate to Android's development?", mark: 5, imp: false },
    { text: "What are the main components of the Android platform?", mark: 10, imp: true },
    { text: "What is the Android SDK, and how is it used to build Android applications?", mark: 10, imp: true },
    { text: "Describe the steps to build a sample Android application.", mark: 10, imp: true },
    { text: "What are the key components of the anatomy of an Android application?", mark: 10, imp: false },
    { text: "Explain the role of Android technologies like Activities, Services, and Broadcast Receivers.", mark: 10, imp: false },
    { text: "What is an Application Context in Android, and why is it important?", mark: 5, imp: false },
    { text: "What are Intents in Android, and how are they used to broadcast and receive messages?", mark: 5, imp: false },
    { text: "What is the Android Manifest file, and what role does it play in application development?", mark: 5, imp: false },
    { text: "What are Intent Filters, and how do they work in Android applications?", mark: 5, imp: false },
    { text: "How do Android applications request and manage permissions?", mark: 5, imp: false },
    { text: "How can an Android application manage resources using a hierarchy?", mark: 5, imp: false },
    { text: "What are the different types of resources an Android application can use?", mark: 5, imp: false },
    { text: "What are the key elements of an Android user interface?", mark: 10, imp: true },
    { text: "How do you design a user interface using layouts in Android?", mark: 10, imp: true },
    { text: "What are the different types of layouts available in Android?", mark: 10, imp: true },
    { text: "Explain the role of Views and ViewGroups in Android UI design.", mark: 10, imp: true },
    { text: "How do you work with XML to create Android user interfaces?", mark: 10, imp: false },
    { text: "What are some best practices for designing Android user interfaces?", mark: 5, imp: false },
    { text: "How can you handle screen orientation changes in Android?", mark: 5, imp: false },
    { text: "Explain the role of styles and themes in Android UI design.", mark: 5, imp: false },
    { text: "What is the importance of material design principles in Android?", mark: 5, imp: false },
    { text: "What is the process for drawing custom views in Android?", mark: 5, imp: false },
    { text: "How do you implement animations in Android?", mark: 5, imp: false },
    { text: "What are the different types of animations available in Android?", mark: 5, imp: false },
    { text: "How can you optimize user interfaces for different screen sizes and densities?", mark: 5, imp: false },
    { text: "What are fragments in Android, and how are they used in user interface design?", mark: 5, imp: false },
    { text: "What is the role of the ConstraintLayout, and why is it preferred in modern Android apps?", mark: 5, imp: false },
    { text: "What are Android APIs, and why are they essential for app development?", mark: 10, imp: true },
    { text: "How can you access and manage data using Android storage APIs?", mark: 10, imp: true },
    { text: "What are Content Providers, and how are they used to share data between applications?", mark: 10, imp: true },
    { text: "Explain the different storage options available in Android (e.g., SharedPreferences, Internal Storage, External Storage).", mark: 10, imp: true },
    { text: "What are SQLite databases, and how are they used in Android applications?", mark: 10, imp: true },
    { text: "How can you manage SQLite databases using Content Providers?", mark: 10, imp: false },
    { text: "What is a Content Resolver, and how does it interact with Content Providers?", mark: 5, imp: false },
    { text: "What are Loaders in Android, and how do they help manage data loading?", mark: 5, imp: false },
    { text: "How can you use the Room persistence library for database management in Android?", mark: 5, imp: false },
    { text: "What is the importance of securing data in Android applications, and what techniques can be used?", mark: 5, imp: false },
    { text: "How do you use Android networking APIs to make network requests?", mark: 10, imp: true },
    { text: "What is the role of the HttpURLConnection class in Android networking?", mark: 5, imp: false },
    { text: "How can you use the Retrofit library to simplify network requests in Android?", mark: 5, imp: false },
    { text: "What is WebView in Android, and how can you use it to display web content?", mark: 5, imp: false },
    { text: "Explain how to handle JSON data in Android applications.", mark: 5, imp: false },
    { text: "What are the different telephony APIs available in Android?", mark: 5, imp: false },
    { text: "How can you send and receive SMS messages using Android telephony APIs?", mark: 5, imp: false },
    { text: "What are the steps to deploy and distribute an Android application?", mark: 5, imp: false },
    { text: "What are the differences between deploying an Android app for development and for production?", mark: 5, imp: false },
    { text: "How do you sign an APK for deployment to the Google Play Store?", mark: 5, imp: false }
];


module.exports=adQuestion;