let dsQuestion = [
    { text: "What is data science, and how do businesses use it to make better decisions?", mark: 10, imp: true },
    { text: "Why is data science important for businesses today, especially with the huge amount of data they collect?", mark: 10, imp: false },
    { text: "How has the meaning of data science changed over the years?", mark: 5, imp: false },
    { text: "What are the four main types of data analysis in data science, and how do they help businesses understand their data?", mark: 10, imp: true },
    { text: "What is predictive analysis, and how can it help businesses predict future trends?", mark: 5, imp: false },
    { text: "How is prescriptive analysis different from predictive analysis, and how does it help businesses take action?", mark: 5, imp: false },
    { text: "What are some benefits of using data science for businesses, like finding hidden patterns and improving processes?", mark: 10, imp: false },
    { text: "What are the steps in the data science process (OSEMN), from collecting data to understanding the results?", mark: 10, imp: false },
    { text: "What are some common data science techniques, like classification, regression, and clustering, and how are they used?", mark: 10, imp: true },
    { text: "How does data science connect with other fields like data engineering, business analytics, and machine learning?", mark: 5, imp: false },
    { text: "What is business analytics, and how does it help companies make better choices?", mark: 5, imp: false },
    { text: "Why do businesses use analytics today?", mark: 5, imp: false },
    { text: "What does 'data-driven decision-making' mean, and why is it important for companies?", mark: 5, imp: true },
    { text: "What is descriptive analytics, and how does it help businesses understand what happened in the past?", mark: 5, imp: false },
    { text: "How does predictive analytics help companies guess what might happen in the future?", mark: 5, imp: false },
    { text: "What is prescriptive analytics, and how does it help businesses figure out the best actions to take?", mark: 5, imp: false },
    { text: "What are some ways businesses use descriptive analytics to learn from their data?", mark: 5, imp: false },
    { text: "How do companies use predictive analytics to make smarter decisions about the future?", mark: 5, imp: false },
    { text: "What are prescriptive analytics techniques, and how do they help businesses choose the right plan?", mark: 5, imp: false },
    { text: "How do descriptive, predictive, and prescriptive analytics work together to help businesses grow?", mark: 5, imp: true },
    { text: "What is big data analytics, and why is it important for businesses?", mark: 5, imp: false },
    { text: "How do companies use web and social media analytics to understand their customers better?", mark: 5, imp: false },
    { text: "What are machine learning algorithms, and how do they help analyze data?", mark: 5, imp: false },
    { text: "What is a framework for data-driven decision-making, and how does it guide businesses?", mark: 5, imp: false },
    { text: "How can businesses build their analytics capabilities to improve decision-making?", mark: 5, imp: false },
    { text: "What steps are involved in creating a roadmap for building analytics capabilities?", mark: 5, imp: false },
    { text: "What are some common challenges businesses face when making decisions based on data?", mark: 5, imp: false },
    { text: "How can organizations overcome the obstacles in data-driven decision-making?", mark: 5, imp: true },
    { text: "What is the future of analytics, and how might it change the way businesses operate?", mark: 5, imp: false },
    { text: "Why is it important for companies to keep improving their analytics skills and tools?", mark: 5, imp: false },
    { text: "What are the different types of data, and how do they differ from each other?", mark: 5, imp: false },
    { text: "What are data measurement scales, and why are they important in analytics?", mark: 5, imp: false },
    { text: "What is the difference between a population and a sample in statistics?", mark: 5, imp: false },
    { text: "What do percentile, decile, and quartile mean, and how do they help describe data?", mark: 5, imp: false },
    { text: "What is a measure of variation, and why is it important to know how spread out the data is?", mark: 5, imp: false },
    { text: "What are some common measures of shape, and what do skewness and kurtosis tell us about data?", mark: 5, imp: false },
    { text: "How can we use descriptive analytics to summarize large sets of data?", mark: 5, imp: false },
    { text: "What types of visualizations can help us understand descriptive analytics better?", mark: 5, imp: false },
    { text: "Why is it useful for businesses to analyze descriptive statistics when making decisions?", mark: 5, imp: true }
];

module.exports=dsQuestion;