let SEques= [
    { text: "What is the evolving role of software in today's world?", mark: 10, imp: true },
    { text: "What is the 'software crisis,' and why is it significant in software development?", mark: 10, imp: true },
    { text: "Discuss common software myths and how they impact software development.", mark: 10, imp: false },
    { text: "What is software engineering, and how is it defined as a layered technology?", mark: 10, imp: true },
    { text: "Explain the basic principles of the Linear Sequential Model.", mark: 10, imp: true },
    { text: "How does the Prototyping Model differ from other software process models?", mark: 10, imp: true },
    { text: "What are the advantages and disadvantages of the RAD (Rapid Application Development) Model?", mark: 10, imp: true },
    { text: "What is the Evolutionary Process Model, and how is it used in software development?", mark: 10, imp: true },
    { text: "Describe the Agile Process Model and its core principles.", mark: 10, imp: true },
    { text: "How is Component-Based Development used in modern software engineering?", mark: 10, imp: true },
    { text: "What are the key elements of the Agile process model?", mark: 10, imp: true },
    { text: "What are the primary practices of Extreme Programming (XP)?", mark: 10, imp: true },
    { text: "Explain how Agile differs from traditional software process models.", mark: 10, imp: true },
    { text: "What are the tools commonly used in Agile development?", mark: 5, imp: false },
    { text: "What are the main differences between iterative and incremental process models?", mark: 10, imp: false },
    { text: "What role do process, practice, and process models play in software development?", mark: 5, imp: false },
    { text: "How does the Prototyping Model improve client communication?", mark: 5, imp: false },
    { text: "Compare and contrast the Waterfall Model and the RAD Model.", mark: 10, imp: false },
    { text: "What is the importance of the Agile Manifesto in software engineering?", mark: 5, imp: false },
    { text: "How do Agile teams adapt to changes in requirements?", mark: 5, imp: false },
    
    { text: "What are the different types of software metrics (process, product, and project)?", mark: 10, imp: true },
    { text: "How do software metrics help in the management of software projects?", mark: 10, imp: true },
    { text: "Explain the process of software project estimation.", mark: 10, imp: true },
    { text: "What are the steps involved in software project planning?", mark: 10, imp: true },
    { text: "How does MS Project help in project scheduling and tracking?", mark: 5, imp: false },
    { text: "What are the key elements of project scheduling?", mark: 5, imp: false },
    { text: "What is risk analysis, and how is it applied in software projects?", mark: 10, imp: false },
    { text: "How is risk identification carried out in software project management?", mark: 5, imp: false },
    { text: "What is risk projection, and why is it important in project management?", mark: 5, imp: false },
    { text: "Explain risk refinement and its role in managing project risks.", mark: 5, imp: false },
    { text: "What are the key strategies for risk mitigation in software projects?", mark: 5, imp: false },
    { text: "Define software requirements and their role in successful project execution.", mark: 10, imp: true },
    { text: "What is the process of requirement elicitation, and how is it carried out?", mark: 10, imp: true },
    { text: "How does requirement analysis impact project success?", mark: 10, imp: true },
    { text: "What is a Software Requirements Specification (SRS), and why is it important?", mark: 10, imp: true },
    { text: "Describe the role of requirement engineering in software project planning.", mark: 10, imp: false },
    { text: "What are the key principles of design concepts in software development?", mark: 10, imp: false },
    { text: "How does architectural design impact the structure of a software project?", mark: 5, imp: false },
    { text: "What is component-level design, and how is it used in modular software development?", mark: 5, imp: false },
    { text: "What are the best practices for user interface design in software engineering?", mark: 5, imp: false },
    { text: "How is web application design different from other types of software design?", mark: 5, imp: false },
    
    { text: "What are coding standards, and why are they important in software development?", mark: 10, imp: true },
    { text: "Explain the importance of following coding guidelines.", mark: 10, imp: true },
    { text: "What is the process and purpose of code review in software development?", mark: 10, imp: true },
    { text: "How is software documentation essential for both development and maintenance?", mark: 5, imp: false },
    { text: "Describe different software testing strategies used in modern software engineering.", mark: 10, imp: true },
    { text: "What are the key components of a test case in software testing?", mark: 5, imp: false },
    { text: "How are test suites designed, and why are they important?", mark: 5, imp: false },
    { text: "What are the key differences between testing conventional applications and testing object-oriented applications?", mark: 5, imp: false },
    { text: "How do you test web and mobile applications, and what tools can be used?", mark: 10, imp: true }
];


module.exports = SEques;