let webFrameworksQuestions = [
    { text: "What is Struts and how does it relate to Struts2?", mark: 10, imp: false },
    { text: "What are the key features of Struts2?", mark: 10, imp: false },
    { text: "Explain the difference between MVC Model 1 and Model 2 architecture.", mark: 10, imp: true },
    { text: "What are the core components of Struts2?", mark: 10, imp: false },
    { text: "What is an interceptor in Struts2, and how does it function?", mark: 10, imp: true },
    { text: "Describe the role of the ValueStack in Struts2.", mark: 5, imp: false },
    { text: "What is ActionContext in Struts2?", mark: 5, imp: false },
    { text: "Explain the ActionInvocation process in Struts2.", mark: 10, imp: true },
    { text: "How does Struts2 integrate with OGNL (Object-Graph Navigation Language)?", mark: 5, imp: false },
    { text: "Describe the overall architecture of Struts2.", mark: 10, imp: false },
    
    // Unit 2: Java Server Faces 2.0
    { text: "What is JSF and what are its key features?", mark: 10, imp: false },
    { text: "Explain the JSF request processing life cycle.", mark: 10, imp: true },
    { text: "How does JSF Expression Language (EL) work?", mark: 10, imp: false },
    { text: "Describe the standard JSF components and their usage.", mark: 10, imp: false },
    { text: "What are Facelets in JSF and how are they different from JSP?", mark: 5, imp: false },
    { text: "What is the purpose of JSF Converter tags?", mark: 5, imp: false },
    { text: "Explain the role of JSF Validation tags.", mark: 5, imp: false },
    { text: "How does event handling work in JSF?", mark: 10, imp: true },
    { text: "Describe how JSF can be used for database access.", mark: 10, imp: true },
    { text: "What are JSF libraries and how do PrimeFaces enhance JSF?", mark: 10, imp: false },
    
    // Unit 3: Hibernate 4.0
    { text: "What is Hibernate and why is it used in Java applications?", mark: 10, imp: false },
    { text: "Explain the architecture of Hibernate.", mark: 10, imp: true },
    { text: "What are the different mapping types in Hibernate?", mark: 10, imp: false },
    { text: "How does object-relational mapping (ORM) work in Hibernate?", mark: 10, imp: false },
    { text: "Describe the use of annotations in Hibernate.", mark: 5, imp: false },
    { text: "What is the Hibernate Query Language (HQL) and how does it differ from SQL?", mark: 10, imp: true },
    { text: "Explain how transactions are managed in Hibernate.", mark: 5, imp: false },
    { text: "What are the advantages of using Hibernate over traditional JDBC?", mark: 10, imp: false },
    { text: "What is lazy loading in Hibernate, and how is it implemented?", mark: 5, imp: false },
    { text: "Describe the lifecycle of a Hibernate session.", mark: 5, imp: false },
    
    // Unit 4: Spring MVC & Spring Boot
    { text: "What is the Spring framework, and why is it popular?", mark: 10, imp: false },
    { text: "Describe the architecture of Spring.", mark: 10, imp: true },
    { text: "What is the lifecycle of a Spring bean?", mark: 5, imp: false },
    { text: "How is XML used in Spring configuration?", mark: 10, imp: false },
    { text: "Explain the concept of Aspect-Oriented Programming (AOP) in Spring.", mark: 10, imp: true },
    { text: "How is database management handled in Spring?", mark: 10, imp: false },
    { text: "What is transaction management in Spring?", mark: 10, imp: false },
    { text: "What is Spring Boot, and how is it different from Spring MVC?", mark: 10, imp: false },
    { text: "Describe the architecture of Spring Boot.", mark: 10, imp: false },
    { text: "Explain the key differences between Spring Boot and Spring MVC.", mark: 10, imp: true },
    { text: "What are the advantages of using Spring Boot over traditional Spring?", mark: 10, imp: false },
    { text: "How do you configure a Spring Boot application?", mark: 10, imp: false },
    { text: "What is the role of embedded servers in Spring Boot?", mark: 5, imp: false },
    { text: "How does Spring Boot simplify dependency management?", mark: 5, imp: false },
    { text: "What is the significance of the @SpringBootApplication annotation?", mark: 5, imp: false },
    { text: "How do you manage profiles in Spring Boot?", mark: 5, imp: false },
    { text: "What is auto-configuration in Spring Boot?", mark: 5, imp: false },
    { text: "How does Spring Boot handle database initialization?", mark: 5, imp: false },
    { text: "Describe the process of creating a REST API using Spring Boot.", mark: 10, imp: true },
    { text: "How do you integrate Spring Boot with Hibernate?", mark: 10, imp: false },
];
module.exports = webFrameworksQuestions;