let aiQuestion = [
    { text: "What is Artificial Intelligence and Artificial Intelligence Technique? Briefly explain how AI techniques can be represented and list out some of the task domains of AI.", mark: 10, imp: true },
    { text: "Enumerate the classical Water Jug Problem. Describe the state space for this problem and give the solution.", mark: 10, imp: false },
    { text: "What is a production system? Explain it with an example. Discuss the characteristics of a production system.", mark: 10, imp: false },
    { text: "How do you define a problem as state space search? Discuss it with the help of an example.", mark: 10, imp: false },
    { text: "Define the following problems and mention the types of control strategies used:\n- The Tower of Hanoi\n- Crypto-arithmetic\n- The Missionaries and Cannibals problem\n- The 8-puzzle problem", mark: 10, imp: false },
    { text: "Discuss the following search techniques with examples. Highlight the benefits and shortcomings of each:\n- Breadth-First Search (BFS)\n- Depth-First Search (DFS)", mark: 10, imp: false },
    { text: "Give an example of a problem for which breadth-first search works better than depth-first search.", mark: 5, imp: true },
    { text: "Explain the algorithm for steepest hill climbing.", mark: 5, imp: false },
    { text: "Explain the following search strategies:\n- Best-First Search\n- A* Search", mark: 10, imp: true },
    { text: "Illustrate the use of predicate logic to represent knowledge with a suitable example.", mark: 10, imp: false },
    { text: "Translate the following sentences into predicate logic, and perform reasoning:\n- John likes all kinds of food.\n- Apples are food.\n- Chicken is food.\n- Anything anyone eats and isn’t killed by is food.\n- Bill eats peanuts and is still alive.\n- Sue eats everything Bill eats.", mark: 10, imp: false },
    { text: "Define heuristic search. Discuss the benefits and shortcomings of heuristic search.", mark: 5, imp: false },
    { text: "Discuss any four of the following heuristic search techniques and explain the algorithms with examples:\n- Hill Climbing (Steepest Ascent)\n- Best-First Search (A* Algorithm)\n- Problem Reduction (AO* Algorithm)\n- Constraint Satisfaction\n- Generate and Test\n- Means-End Analysis", mark: 10, imp: false },
    { text: "Solve the following crypt-arithmetic problem using the constraint satisfaction search procedure:\n- CROSS + ROADS = DANGER", mark: 10, imp: false },
    { text: "Explain the difference between procedural and declarative knowledge.", mark: 5, imp: false },
    { text: "Discuss various approaches and issues in knowledge representation. What are the problems in representing knowledge?", mark: 5, imp: false },
    { text: "Explain the algorithm for predicate logic resolution.", mark: 5, imp: true },
    { text: "Write and explain the unification algorithm for predicate logic resolution.", mark: 5, imp: false },
    { text: "Explain Non-Monotonic reasoning and discuss the logics associated with it.", mark: 5, imp: false },
    { text: "Explain the AO* algorithm with an example.", mark: 5, imp: false },
    { text: "Explain how a constraint satisfaction problem (CSP) may be solved.", mark: 5, imp: false },
    { text: "Explain the resolution procedure in detail.", mark: 5, imp: false },
    { text: "Represent the following statements in predicate logic:\n- Marcus tried to assassinate Caesar.\n- All Pompeians were Roman.\n- All Romans were either loyal to Caesar or hated him.\n- Everyone is loyal to someone.\n- People only try to assassinate rulers they are not loyal to.", mark: 10, imp: false },
    { text: "What is non-monotonic reasoning? Explain the logics used for non-monotonic reasoning.", mark: 5, imp: false },
    { text: "What are scripts? Explain in detail with an example.", mark: 5, imp: false },
    { text: "Write a short note on:\n- Expert Systems\n- Knowledge Acquisition", mark: 5, imp: false },
    { text: "What is an AND graph and OR graph? Explain the A* algorithm with an example.", mark: 5, imp: false },
    { text: "Explain conceptual dependency with an example and build up the conceptual dependency structures for the following sentences:\n- John pushed the cart.\n- John took the book from Mary.\n- While going home, I saw a frog.", mark: 10, imp: true },
    { text: "Give the steps involved in converting wff predicates into clause form with examples.", mark: 5, imp: false },
    { text: "Write a short note on:\n- Justification-Based Truth Maintenance Systems (JTMS)\n- Logic-Based Truth Maintenance Systems (LTMS)", mark: 5, imp: false },
    { text: "Discuss the heuristic function and explain how it helps during search procedures with a suitable example.", mark: 5, imp: false },
    { text: "What are the different types of problems addressed by AI, and how are they classified?", mark: 10, imp: true },
    { text: "Explain various AI techniques and their real-world applications.", mark: 10, imp: false },
    { text: "Discuss the different levels of models in AI. How are they used in AI problem-solving?", mark: 10, imp: true },
    { text: "What are the criteria for success in AI systems, and how can these criteria be evaluated?", mark: 10, imp: false },
    { text: "How do you define a problem as state space search? Provide an example to explain the concept.", mark: 10, imp: false },
    { text: "Discuss heuristic search techniques and explain their importance in AI problem-solving.", mark: 10, imp: false },
    { text: "Explain production systems in AI with examples and their characteristics.", mark: 10, imp: false },
    { text: "What is hill climbing, and how does it work as a search technique? Explain with an example.", mark: 10, imp: true },
    { text: "Discuss means-end analysis and its role in AI problem-solving.", mark: 10, imp: false },
    { text: "What are the different approaches to knowledge representation in AI?", mark: 10, imp: false },
    { text: "Explain the difference between procedural and declarative knowledge with examples.", mark: 10, imp: true },
    { text: "How does predicate logic help in knowledge representation? Illustrate with an example.", mark: 10, imp: false },
    { text: "What is forward and backward reasoning in AI, and how are they applied?", mark: 10, imp: false },
    { text: "What is non-monotonic reasoning? Discuss the logics used for non-monotonic reasoning.", mark: 10, imp: false },
    { text: "Explain the structure and working of an expert system. What are its components?", mark: 10, imp: false },
    { text: "Convert English sentences into Prolog facts and rules. How is this useful in AI problem-solving?", mark: 10, imp: true },
    { text: "Discuss reasoning under uncertainty and explain how symbolic reasoning differs from logical reasoning.", mark: 10, imp: false }
];

module.exports= aiQuestion;