let Dmques = [
    { text: "What is data mining, and why is it important?", mark: 10, imp: true },
    { text: "Explain the different functionalities of data mining.", mark: 5, imp: true },
    { text: "How are data mining systems classified?", mark: 5, imp: true },
    { text: "What are the main tasks performed in data mining?", mark: 5, imp: true },
    { text: "Define data mining and its role in knowledge discovery (KDD).", mark: 10, imp: true },
    { text: "What are the integration challenges of a data mining system with a database or data warehouse?", mark: 5, imp: true },
    { text: "What are the key issues in data mining?", mark: 10, imp: true },
    { text: "Explain the process of Knowledge Discovery in Databases (KDD).", mark: 5, imp: false },
    { text: "What is data summarization, and why is it necessary?", mark: 5, imp: false },
    { text: "Describe the process of data cleaning and its importance in data mining.", mark: 10, imp: true },
    { text: "What is data integration, and how does it impact data mining?", mark: 5, imp: false },
    { text: "Explain data transformation and its significance in data pre-processing.", mark: 5, imp: false },
    { text: "What is data reduction, and how does it affect data mining processes?", mark: 10, imp: true },
    { text: "Describe data discretization and concept hierarchy generation.", mark: 5, imp: true },
    { text: "What is feature extraction, and how is it performed in data mining?", mark: 5, imp: true },
    { text: "Explain the process and importance of feature transformation in data mining.", mark: 5, imp: true },
    { text: "What is feature selection, and why is it important?", mark: 10, imp: true },
    { text: "Describe the concept of dimensionality reduction and its benefits.", mark: 5, imp: true },
    { text: "What is CUR decomposition, and how is it applied in data mining?", mark: 5, imp: false },
    { text: "What is concept description in data mining?", mark: 10, imp: true },
    { text: "Explain data generalization and its role in concept description.", mark: 10, imp: true },
    { text: "How is data summarization performed using characterization?", mark: 5, imp: true },
    { text: "What is attribute relevance, and how is it determined?", mark: 5, imp: false },
    { text: "Describe the process of class comparison in data mining.", mark: 5, imp: false },
    { text: "Explain the concept of frequent itemset mining.", mark: 10, imp: true },
    { text: "What are the different kinds of association rules in data mining?", mark: 10, imp: true },
    { text: "How do we transition from association rule mining to correlation analysis?", mark: 5, imp: true },
    { text: "What are advanced association rule techniques?", mark: 5, imp: false },
    { text: "How is the quality of rules measured in association rule mining?", mark: 10, imp: true },
    { text: "What is classification in data mining?", mark: 10, imp: true },
    { text: "Explain prediction in the context of data mining.", mark: 5, imp: true },
    { text: "What are the key issues related to classification and prediction?", mark: 10, imp: true },
    { text: "Describe statistical-based classification algorithms.", mark: 5, imp: false },
    { text: "What are distance-based classification algorithms?", mark: 5, imp: false },
    { text: "How do decision tree-based algorithms work?", mark: 10, imp: true },
    { text: "Explain neural network-based algorithms for classification.", mark: 10, imp: true },
    { text: "What are rule-based algorithms in data mining?", mark: 5, imp: false },
    { text: "Describe the common training techniques used in classification models.", mark: 5, imp: false },
    { text: "What are the common error measures used in classification and prediction?", mark: 5, imp: true },
    { text: "How is the accuracy of a classifier or predictor evaluated?", mark: 10, imp: true },
    { text: "Describe the role of neural networks in prediction.", mark: 10, imp: true },
    { text: "What is linear regression, and how is it used for prediction?", mark: 10, imp: true },
    { text: "Explain non-linear regression and its applications in data mining.", mark: 5, imp: false },
    { text: "What is logistic regression, and how is it used in data mining?", mark: 10, imp: true },
    { text: "What are the common tools used for classification and prediction in data mining?", mark: 5, imp: false },
    { text: "How is feature selection applied in classification tasks?", mark: 5, imp: true },
    { text: "What are the challenges of data pre-processing in data mining?", mark: 10, imp: true },
    { text: "How does CUR decomposition help in reducing data dimensionality?", mark: 5, imp: false },
    { text: "What are some of the most common data mining techniques used in industry today?", mark: 10, imp: true }
];

module.exports = Dmques;